### ISSUE TITLE
Saurian Oracle needs way too little XP to advance to level 3.

### ISSUE THREAD

**Issue by knyghtmare** [czyzby/wesnoth-saurian-pack#8]
https://github.com/czyzby/wesnoth-saurian-pack/blob/3d4bcbe4336d362855d8ef0ed40b069e08404162/_main.cfg#L27

May I request that this XP value be set to like something a bit higher, like for all mage-like units? 

```ini
    set_experience=98
```
Or, something between XP 85-100? 50 seems way too little for a level 2 to go to level 3. 
On comparison, I have it set to 98 in my add-on.

**Comment by czyzby** [comment]
Oracle is much weaker than other Lv2 mages. The experience needed to advance was based on the other saurian units, i.e. Augur to Oracle and Ambusher to Flanker.

Unit | Level | Experience 
--- | --- | ---
Elvish Shaman | 1 | 32
Elvish Druid | 2 | 80
Mage | 1 | 54 
Red Mage | 2 | 100
Saurian Augur | 1 | 28
Saurian Skirmisher | 1 | 32
Saurian Ambusher | 2 | 55

Augur advances faster than Skirmisher, and Ambusher requires only 55 experience to advance to level 3. While I agree that offensive spellcasters seem to require more experience on average to advance, and 50 might be a bit too low, I think it should still be in 65-75 range rather than 85+. After all, Oracle deals 3/4 of Red Mage's damage and is much more fragile.

**Comment by knyghtmare** [comment]
You make a solid argument. Then perhaps:

```
 set_experience=66
```
I will also make this adjustment in my add-on(s).

**Comment by czyzby** [comment]
66 sounds good.

**Comment by czyzby** [comment]
I've adjusted the advancement experience to 66. Are there any other balancing suggestions that you have in mind?

**Comment by knyghtmare** [comment]
> I've adjusted the advancement experience to 66. Are there any other balancing suggestions that you have in mind?

I would say the Prophet's ranged attack seems to have gained quite a damage increase (+4, but yeah, it's fine).

I wonder if I can push these advancements into the drake campaign by promoting them in a play-through as Saurians are gained from S5 onwards and stay till the end. One advancement for the Soothsayer would be nice as it's one of the hero units and lacks AMLA and just ends up being a backline healer role.

**Comment by czyzby** [comment]
> I would say the Prophet's ranged attack seems to have gained quite a damage increase (+4, but yeah, it's fine).

It's similar to the Mage line. Red Mage deals 4-8, while Arch Mage deals 4-12. Since Saurian Oracle deals 3-8, I think it's reasonable for Saurian Prophet to deal 3-12. I don't think it's overpowered for a level 3 unit by any means.

> I wonder if I can push these advancements into the drake campaign by promoting them in a play-through as Saurians are gained from S5 onwards and stay till the end.

I'll modify the configuration to make the mod available for campaigns. Making the advancements optional would probably be the best option.

> One advancement for the Soothsayer would be nice as it's one of the hero units and lacks AMLA and just ends up being a backline healer role.

I considered making one, but mechanically I quite like them as they are - you either go for a backline healer, like you said, or for an offensive line with more damage potential. I'll think about it though.
